[project]
name = "smartdata2026-qr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sergeyz06", email = "sergeyz06@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "datapipe-core==0.15.0",
    "fsspec>=2026.7.0",
    "polars>=1.44.2",
    "pyarrow==25.0.1",
    "pysqlite3==0.6.0",
    "pysqlite3-binary==0.5.4.post2",
    "sqlalchemy-pysqlite3-binary==0.0.4",
]

[project.scripts]
smartdata2026-qr = "smartdata2026_qr:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
